test: &default

  # Credentials for REST APIs
  client_id: ASz27ljDY7DLDi4QTgoIulpN2upVxR0-hcIQxvgdEJ5uwYLXNgvtx9ebUOLtxl4TLWg-p08HlpK_YTA1

  client_secret: EEkwam-K1LoZfL8mak2bns5jIKoPs_L7XyaoshsqPV8exJtFQnPSQwtwURbAmWeXlwDPtWFjkW5mXqpp

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: malo_s8a1@hotmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
